apiVersion: v1
kind: ConfigMap
metadata:
  nginx.conf: |
    server {
    listen       80 default_server;
    server_name  localhost _;
    index        index.html index.htm;
    root         /code;

    location / {
        autoindex on;
    }
}
