apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-client    # kubectl get sc 에서 확인한 storageClassName 을 입력 합니다.
  volumeMode: Filesystem
